Repository xaehub/Spring-Rider, pull requests merged in 2025-04, with the labels that each got.

#2 [#1] 공통 응답 형식 제공
  src/main/java/com/example/springrider/domain/common/exception/BaseException.java
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
  src/main/java/com/example/springrider/domain/common/handler/GlobalExceptionHandler.java
  src/main/java/com/example/springrider/domain/common/response/ApiResponse.java
  src/main/java/com/example/springrider/domain/common/response/ErrorResponse.java
  src/main/java/com/example/springrider/domain/common/response/ResponseInterceptor.java
  src/main/java/com/example/springrider/domain/menu/controller/MenuController.java
  src/main/java/com/example/springrider/domain/store/controller/StoreController.java
  src/main/java/com/example/springrider/domain/user/controller/UserController.java
  src/main/java/com/example/springrider/domain/user/service/UserService.java
Labels: feature, refactoring

#4 [#3 ] Refactor: 회원가입 및 로그인 DTO 유효성 검증 및 서비스 응답 구조 개선
  src/main/java/com/example/springrider/domain/user/dto/LoginRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/SignupRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/UserResponseDto.java
  src/main/java/com/example/springrider/domain/user/entity/User.java
Labels: feature, refactoring

#11 [#10] feat: 회원탈퇴 기능 구현 및 응답 메시지 정리
  src/main/java/com/example/springrider/domain/user/controller/UserController.java
  src/main/java/com/example/springrider/domain/user/dto/request/DeleteUserRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/request/LoginRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/request/SignupRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/LoginResponseDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/SignupResponseDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/WithdrawResponseDto.java
  src/main/java/com/example/springrider/domain/user/service/UserService.java
Labels: feature

#13 [#12] feat: 전체 가게 조회 기능 추가
  .gitignore
  src/main/java/com/example/springrider/domain/store/controller/StoreController.java
  src/main/java/com/example/springrider/domain/store/dto/StoreSimpleResponseDto.java
  src/main/java/com/example/springrider/domain/store/repository/StoreRepository.java
  src/main/java/com/example/springrider/domain/store/service/StoreService.java
Labels: feature

#17 [#8] Feat/cart domain entity,enum
  src/main/java/com/example/springrider/domain/cart/entity/CartItem.java
  src/main/java/com/example/springrider/domain/cart/enums/CartItemStatus.java
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
Labels: feature

#18 [#15] 유저 회원가입 시 응답 데이터 수정
  src/main/java/com/example/springrider/domain/user/service/UserService.java
Labels: bug, fix

#20 [#19] 메뉴 등록
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
  src/main/java/com/example/springrider/domain/menu/controller/MenuController.java
  src/main/java/com/example/springrider/domain/menu/dto/MenuRequestDto.java
  src/main/java/com/example/springrider/domain/menu/dto/MenuResponseDto.java
  src/main/java/com/example/springrider/domain/menu/dto/MenuSaveResponseDto.java
  src/main/java/com/example/springrider/domain/menu/entity/Menu.java
  src/main/java/com/example/springrider/domain/menu/repository/MenuRepository.java
  src/main/java/com/example/springrider/domain/menu/service/MenuService.java
Labels: feature

#21 [#이슈없음] default 메소드 활용하도록 리팩토링
  src/main/java/com/example/springrider/domain/menu/service/MenuService.java
  src/main/java/com/example/springrider/domain/store/repository/StoreRepository.java
  src/main/java/com/example/springrider/domain/store/service/StoreService.java
  src/main/java/com/example/springrider/domain/user/repository/UserRepository.java
  src/main/java/com/example/springrider/domain/user/service/UserService.java
Labels: refactoring

#22 [#14] Feat/get store
  src/main/java/com/example/springrider/domain/store/controller/StoreController.java
  src/main/java/com/example/springrider/domain/store/dto/StoreDetailResponseDto.java
  src/main/java/com/example/springrider/domain/store/service/StoreService.java
Labels: feature

#26 [#23] feat: 가게 생성 기능 수정
  src/main/java/com/example/springrider/domain/store/controller/StoreController.java
  src/main/java/com/example/springrider/domain/store/dto/StoreResponseDto.java
  src/main/java/com/example/springrider/domain/store/entity/Store.java
  src/main/java/com/example/springrider/domain/store/service/StoreService.java
Labels: feature

#27 [9] 메뉴 삭제 기능 구현
  src/main/java/com/example/springrider/domain/menu/controller/MenuController.java
  src/main/java/com/example/springrider/domain/menu/dto/MenuResponseDto.java
  src/main/java/com/example/springrider/domain/menu/entity/Menu.java
  src/main/java/com/example/springrider/domain/menu/service/MenuService.java
Labels: feature

#32 [#30] feat: 가게 수정 시 생기는 이슈 수정
  src/main/java/com/example/springrider/domain/store/controller/StoreController.java
  src/main/java/com/example/springrider/domain/store/service/StoreService.java
Labels: feature

#35 [#7] feat: add cart api
  src/main/java/com/example/springrider/domain/cart/controller/CartController.java
  src/main/java/com/example/springrider/domain/cart/dto/CartItemBulkRequestDto.java
  src/main/java/com/example/springrider/domain/cart/dto/CartItemBulkResponseDto.java
  src/main/java/com/example/springrider/domain/cart/dto/CartItemRequestDto.java
  src/main/java/com/example/springrider/domain/cart/dto/FailedItemDto.java
  src/main/java/com/example/springrider/domain/cart/dto/SuccessItemDto.java
  src/main/java/com/example/springrider/domain/cart/entity/CartItem.java
  src/main/java/com/example/springrider/domain/cart/repository/CartRepository.java
  src/main/java/com/example/springrider/domain/cart/service/CartService.java
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
  src/main/java/com/example/springrider/domain/common/exception/InvalidRequestException.java
Labels: feature

#36 [#33] feat: 다루지 못하는 예외 Exception 에서 다루는 코드 추가
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
  src/main/java/com/example/springrider/domain/common/handler/GlobalExceptionHandler.java
Labels: feature

#42 [# 노이슈] comments: 전체적인 주석 수정 및 가게 다건, 단건 기능 주석 추가
  src/main/java/com/example/springrider/domain/store/controller/StoreController.java
  src/main/java/com/example/springrider/domain/store/service/StoreService.java
Labels: feature

#46 [#45] feat: entity에 nullable 추가
  src/main/java/com/example/springrider/domain/store/entity/Store.java
Labels: feature

#44 [# 40] fix:로그인 중복체크 수정
  src/main/java/com/example/springrider/config/filter/SessionLoginCheckFilter.java
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
  src/main/java/com/example/springrider/domain/user/service/UserService.java
Labels: fix

#55 [#38 ] fix:회원탈퇴 버그 수정
  src/main/java/com/example/springrider/config/filter/SessionLoginCheckFilter.java
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
  src/main/java/com/example/springrider/domain/user/controller/UserController.java
  src/main/java/com/example/springrider/domain/user/entity/User.java
  src/main/java/com/example/springrider/domain/user/service/UserService.java
Labels: fix

#56 [#이슈없음] refactor: 전반적인 코드 수정
  src/main/java/com/example/springrider/domain/store/controller/StoreController.java
  src/main/java/com/example/springrider/domain/store/service/StoreService.java
  src/main/java/com/example/springrider/domain/user/controller/UserController.java
  src/main/java/com/example/springrider/domain/user/dto/response/LoginResponseDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/SignupResponseDto.java
  src/main/java/com/example/springrider/domain/user/entity/User.java
  src/main/java/com/example/springrider/domain/user/service/UserService.java
Labels: feature

#52 [#37] Feat/search cart
  src/main/java/com/example/springrider/domain/cart/controller/CartController.java
  src/main/java/com/example/springrider/domain/cart/dto/CartItemSearchBulkResponseDto.java
  src/main/java/com/example/springrider/domain/cart/dto/CartItemSearchResponseDto.java
  src/main/java/com/example/springrider/domain/cart/repository/CartRepository.java
  src/main/java/com/example/springrider/domain/cart/service/CartService.java
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
Labels: feature

#58 [#54] Feat/order entity and order item entity
  src/main/java/com/example/springrider/domain/cart/entity/CartItem.java
  src/main/java/com/example/springrider/domain/order/entity/Order.java
  src/main/java/com/example/springrider/domain/order/entity/OrderItem.java
Labels: feature

#65 [#43] test: 가게 생성 테스트 코드 작성
  src/main/java/com/example/springrider/domain/store/controller/StoreController.java
  src/main/java/com/example/springrider/domain/store/dto/FindStoreResponseDto.java
  src/main/java/com/example/springrider/domain/store/dto/FindStoresResponseDto.java
  src/main/java/com/example/springrider/domain/store/dto/UpdateStoreRequestDto.java
  src/main/java/com/example/springrider/domain/store/entity/Store.java
  src/main/java/com/example/springrider/domain/store/service/StoreService.java
  src/test/java/com/example/springrider/domain/store/controller/StoreControllerTest.java
  src/test/java/com/example/springrider/domain/store/service/StoreServiceTest.java
Labels: refactoring, test

#66 [#48] fix: 주문 생성 시 가게 정보 조회되지 않는 현상 수정
  src/main/java/com/example/springrider/domain/order/service/UserOrderService.java
Labels: fix

#68 [#69] refactor: 엔티티의 문자열 필드에 length 속성 추가
  src/main/java/com/example/springrider/aop/StoreOwnerCheck.java
  src/main/java/com/example/springrider/aop/StoreOwnerCheckAspect.java
  src/main/java/com/example/springrider/domain/menu/controller/MenuController.java
  src/main/java/com/example/springrider/domain/menu/entity/Menu.java
  src/main/java/com/example/springrider/domain/menu/service/MenuService.java
  src/main/java/com/example/springrider/domain/order/entity/Order.java
  src/main/java/com/example/springrider/domain/review/entity/Review.java
  src/main/java/com/example/springrider/domain/store/entity/Store.java
  src/main/java/com/example/springrider/domain/user/entity/User.java
Labels: feature, refactoring

#77 [#76] test: 가게 생성 시 3개를 초과하면 예외
  src/test/java/com/example/springrider/domain/store/service/StoreServiceTest.java
Labels: test

#81 [#79] test: 가게가 정상적으로 수정된다
  src/test/java/com/example/springrider/domain/store/service/StoreServiceTest.java
Labels: test

#78 [#59] Feat/cart update api
  src/main/java/com/example/springrider/domain/cart/controller/CartController.java
  src/main/java/com/example/springrider/domain/cart/dto/CreateCartItemBulkRequestDto.java
  src/main/java/com/example/springrider/domain/cart/dto/CreateCartItemBulkResponseDto.java
  src/main/java/com/example/springrider/domain/cart/dto/CreateCartItemRequestDto.java
  src/main/java/com/example/springrider/domain/cart/dto/FindCartItemBulkResponseDto.java
  src/main/java/com/example/springrider/domain/cart/dto/FindCartItemResponseDto.java
  src/main/java/com/example/springrider/domain/cart/dto/UpdateCartItemRequestDto.java
  src/main/java/com/example/springrider/domain/cart/dto/UpdateCartItemResponseDto.java
  src/main/java/com/example/springrider/domain/cart/entity/CartItem.java
  src/main/java/com/example/springrider/domain/cart/enums/CartItemStatus.java
  src/main/java/com/example/springrider/domain/cart/repository/CartRepository.java
  src/main/java/com/example/springrider/domain/cart/service/CartService.java
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
  src/main/java/com/example/springrider/global/validation/NotAllNull.java
  src/main/java/com/example/springrider/global/validation/NotAllNullValidator.java
Labels: feature

#80 [#48] feat: 주문 생성 시 AOP에 의한 로깅 추가
  src/main/java/com/example/springrider/aop/OrderEventLog.java
  src/main/java/com/example/springrider/aop/OrderEventLogAspect.java
  src/main/java/com/example/springrider/aop/StoreOwnerCheckAspect.java
  src/main/java/com/example/springrider/domain/order/repository/OrderRepository.java
  src/main/java/com/example/springrider/domain/order/service/UserOrderService.java
  src/main/java/com/example/springrider/domain/store/service/StoreService.java
Labels: feature

#85 [#84] test: 가게 수정 시 예외 처리
  src/test/java/com/example/springrider/domain/store/service/StoreServiceTest.java
Labels: test

#88 [#86] refactoring: 테스트 코드 수정
  src/test/java/com/example/springrider/domain/store/service/StoreServiceTest.java
Labels: test

#91 [# 64] 유저 서비스 및 컨트롤러 테스트 코드
  src/main/java/com/example/springrider/domain/common/handler/GlobalExceptionHandler.java
  src/main/java/com/example/springrider/domain/user/controller/UserController.java
  src/main/java/com/example/springrider/domain/user/dto/request/DeleteUserRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/request/LoginRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/request/PasswordModifyRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/request/ProfileModifyRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/request/SignupRequestDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/LoginResponseDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/SignupResponseDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/springrider/domain/user/service/UserService.java
  src/test/java/com/example/springrider/user/controller/controller/UserControllerTest.java
  src/test/java/com/example/springrider/user/controller/service/UserServiceTest.java
Labels: test

#90 [#49] 유저 주문 목록 조회 API
  src/main/java/com/example/springrider/aop/OrderEventLogAspect.java
  src/main/java/com/example/springrider/domain/order/controller/UserOrderController.java
  src/main/java/com/example/springrider/domain/order/dto/OrderResponseDto.java
  src/main/java/com/example/springrider/domain/order/repository/OrderRepository.java
  src/main/java/com/example/springrider/domain/order/service/UserOrderService.java
Labels: feature

#95 [#90, #53] Fix/cart delete bug, Feat/ Owner order status update
  src/main/java/com/example/springrider/domain/cart/repository/CartRepository.java
  src/main/java/com/example/springrider/domain/cart/service/CartService.java
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
  src/main/java/com/example/springrider/domain/order/controller/OwnerOrderController.java
  src/main/java/com/example/springrider/domain/order/controller/UserOrderController.java
  src/main/java/com/example/springrider/domain/order/dto/OrderResponseDto.java
  src/main/java/com/example/springrider/domain/order/dto/UpdateOrderStatusRequestDto.java
  src/main/java/com/example/springrider/domain/order/dto/UpdateOrderStatusResponseDto.java
  src/main/java/com/example/springrider/domain/order/entity/Order.java
  src/main/java/com/example/springrider/domain/order/enums/OrderStatus.java
  src/main/java/com/example/springrider/domain/order/service/OwnerOrderService.java
Labels: feature, bug

#96 [#48] fix: 주문 생성 시 status가 입력되지 않는 문제 해결
  src/main/java/com/example/springrider/domain/order/entity/Order.java
Labels: fix

#104 [#101] test: 가게 단건 조회
  src/test/java/com/example/springrider/domain/store/service/StoreServiceTest.java
Labels: test

#103 [#51] feat: 사장 주문 목록 조회 기능 구현 feature 기능 추가
  src/main/java/com/example/springrider/aop/OrderEventLogAspect.java
  src/main/java/com/example/springrider/domain/order/controller/OwnerOrderController.java
  src/main/java/com/example/springrider/domain/order/controller/UserOrderController.java
  src/main/java/com/example/springrider/domain/order/dto/OrderResponseDto.java
  src/main/java/com/example/springrider/domain/order/dto/request/CreateOrderRequestDto.java
  src/main/java/com/example/springrider/domain/order/dto/request/UpdateOrderStatusRequestDto.java
  src/main/java/com/example/springrider/domain/order/dto/request/UpdateOrderStatusResponseDto.java
  src/main/java/com/example/springrider/domain/order/dto/response/OrderResponseDto.java
  src/main/java/com/example/springrider/domain/order/dto/response/OwnerOrderResponseDto.java
  src/main/java/com/example/springrider/domain/order/repository/OrderRepository.java
  src/main/java/com/example/springrider/domain/order/service/OwnerOrderService.java
  src/main/java/com/example/springrider/domain/order/service/UserOrderService.java
Labels: feature

#98 [#97] Feat/enum valid custom annotation
  src/main/java/com/example/springrider/domain/cart/dto/UpdateCartItemRequestDto.java
  src/main/java/com/example/springrider/domain/common/handler/GlobalExceptionHandler.java
  src/main/java/com/example/springrider/domain/order/dto/request/UpdateOrderStatusRequestDto.java
  src/main/java/com/example/springrider/global/validation/EnumValid.java
  src/main/java/com/example/springrider/global/validation/EnumValidator.java
Labels: feature

#105 [#102] test: 가게 단건 조회 시 폐업인 가게를 조회하면 예외를 던진다
  src/test/java/com/example/springrider/domain/store/service/StoreServiceTest.java
Labels: test

#107 [#106] test: 가게 수정 시 마감 시간이 오픈 시간보다 빠를 때 예외
  src/test/java/com/example/springrider/domain/store/service/StoreServiceTest.java
Labels: test

#108 [#99] Feat/owner order cancel api
  src/main/java/com/example/springrider/domain/common/exception/ExceptionCode.java
  src/main/java/com/example/springrider/domain/order/controller/OwnerOrderController.java
  src/main/java/com/example/springrider/domain/order/dto/request/CancelOrderRequestDto.java
  src/main/java/com/example/springrider/domain/order/dto/response/CancelOrderResponseDto.java
  src/main/java/com/example/springrider/domain/order/dto/response/UpdateOrderStatusResponseDto.java
  src/main/java/com/example/springrider/domain/order/entity/Order.java
  src/main/java/com/example/springrider/domain/order/enums/OrderCancelReason.java
  src/main/java/com/example/springrider/domain/order/enums/OrderStatus.java
  src/main/java/com/example/springrider/domain/order/service/OwnerOrderService.java
  src/main/java/com/example/springrider/global/validation/EnumValidator.java
Labels: feature

#112 [#111] test: 메뉴 생성
  src/test/java/com/example/springrider/domain/menu/service/MenuServiceTest.java
Labels: test

#116 [#113] test: 메뉴 수정
  src/test/java/com/example/springrider/domain/menu/service/MenuServiceTest.java
Labels: test

#117 [#114] test: 메뉴 삭제
  src/test/java/com/example/springrider/domain/menu/service/MenuServiceTest.java
Labels: test

#121 [#82] dto 클래스 내부 로직 통일 (정적 팩토리 메서드 활용 및 네이밍 일원화)
  src/main/java/com/example/springrider/domain/cart/dto/response/FindCartItemBulkResponseDto.java
  src/main/java/com/example/springrider/domain/cart/dto/response/FindCartItemResponseDto.java
  src/main/java/com/example/springrider/domain/cart/dto/response/UpdateCartItemResponseDto.java
  src/main/java/com/example/springrider/domain/cart/service/CartService.java
  src/main/java/com/example/springrider/domain/menu/dto/response/MenuResponseDto.java
  src/main/java/com/example/springrider/domain/menu/service/MenuService.java
  src/main/java/com/example/springrider/domain/order/dto/response/CancelOrderResponseDto.java
  src/main/java/com/example/springrider/domain/order/dto/response/UpdateOrderStatusResponseDto.java
  src/main/java/com/example/springrider/domain/order/service/OwnerOrderService.java
  src/main/java/com/example/springrider/domain/store/dto/response/FindAllStoreResponseDto.java
  src/main/java/com/example/springrider/domain/store/dto/response/FindStoreResponseDto.java
  src/main/java/com/example/springrider/domain/store/dto/response/StoreResponseDto.java
  src/main/java/com/example/springrider/domain/store/service/OwnerStoreService.java
  src/main/java/com/example/springrider/domain/store/service/UserStoreService.java
  src/main/java/com/example/springrider/domain/user/dto/response/LoginResponseDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/SignupResponseDto.java
  src/main/java/com/example/springrider/domain/user/dto/response/UserResponseDto.java
Labels: refactoring

#123 [# 67] refactor: 하드코딩 제거 및 상수화
  src/main/java/com/example/springrider/config/Const.java
  src/main/java/com/example/springrider/config/filter/SessionLoginCheckFilter.java
  src/test/java/com/example/springrider/domain/user/controller/UserControllerTest.java
  src/test/java/com/example/springrider/domain/user/service/UserServiceTest.java
Labels: refactoring

#125 [# 124] refactor:유저 컨트롤러 테스트코드 리팩터링
  src/test/java/com/example/springrider/domain/user/controller/UserControllerTest.java
Labels: refactoring

#122 [#110] Feat/customer review create api
  src/main/java/com/example/springrider/domain/cart/service/CartService.java
  src/main/java/com/example/springrider/domain/order/enums/OrderStatus.java
  src/main/java/com/example/springrider/domain/order/repository/OrderRepository.java
  src/main/java/com/example/springrider/domain/order/service/UserOrderService.java
  src/main/java/com/example/springrider/domain/review/controller/ReviewController.java
  src/main/java/com/example/springrider/domain/review/dto/request/CreateReviewRequestDto.java
  src/main/java/com/example/springrider/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/example/springrider/domain/review/entity/Review.java
  src/main/java/com/example/springrider/domain/review/enums/Rating.java
  src/main/java/com/example/springrider/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/springrider/domain/review/service/ReviewService.java
  src/main/java/com/example/springrider/global/exception/ExceptionCode.java
Labels: feature

#126 [# 67] refactor: 서비스,컨트롤러 세션 리팩터링
  src/main/java/com/example/springrider/domain/user/controller/UserController.java
  src/main/java/com/example/springrider/domain/user/service/UserService.java
  src/test/java/com/example/springrider/domain/user/controller/UserControllerTest.java
  src/test/java/com/example/springrider/domain/user/service/UserServiceTest.java
Labels: refactoring

#127 [# 67] refactor: 오너인터셉터 리팩터링
  src/main/java/com/example/springrider/config/interceptor/StoreOwnerInterceptor.java
  src/main/java/com/example/springrider/domain/user/service/UserService.java
Labels: refactoring

#128 [# 115] refactor: 프로필수정시 유저정보 응답 설정
  src/main/java/com/example/springrider/domain/user/controller/UserController.java
Labels: refactoring

#133 [#67] 세션 유저 아이디 상수로 사용하도록 수정
  src/main/java/com/example/springrider/config/filter/SessionLoginCheckFilter.java
  src/main/java/com/example/springrider/config/interceptor/StoreOwnerInterceptor.java
  src/main/java/com/example/springrider/domain/cart/controller/CartController.java
  src/main/java/com/example/springrider/domain/menu/controller/MenuController.java
  src/main/java/com/example/springrider/domain/order/controller/OwnerOrderController.java
  src/main/java/com/example/springrider/domain/order/controller/UserOrderController.java
  src/main/java/com/example/springrider/domain/review/controller/ReviewController.java
  src/main/java/com/example/springrider/domain/store/controller/OwnerStoreController.java
  src/main/java/com/example/springrider/domain/user/controller/UserController.java
Labels: refactoring

#132 [#129] Feat/cart initialize regular
  src/main/java/com/example/springrider/SpringRiderApplication.java
  src/main/java/com/example/springrider/domain/cart/repository/CartRepository.java
  src/main/java/com/example/springrider/domain/cart/service/CartService.java
  src/main/java/com/example/springrider/domain/order/service/UserOrderService.java
Labels: feature

#136 [# 115] feat: 회원 탈퇴시 이메일 불일치 처리 예외 메시지 수정 및 예외메시지 추가
  src/main/java/com/example/springrider/domain/user/service/UserService.java
  src/main/java/com/example/springrider/global/exception/ExceptionCode.java
Labels: feature

#137 [#134] Feat/review read api
  src/main/java/com/example/springrider/domain/order/entity/Order.java
  src/main/java/com/example/springrider/domain/review/controller/ReviewController.java
  src/main/java/com/example/springrider/domain/review/dto/response/FindAllReviewResponseDto.java
  src/main/java/com/example/springrider/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/springrider/domain/review/service/ReviewService.java
  src/main/java/com/example/springrider/domain/store/entity/Store.java
  src/main/java/com/example/springrider/global/exception/ExceptionCode.java
Labels: feature

#138 [#115] fix: 메뉴 reqeust dto 수정
  src/main/java/com/example/springrider/domain/menu/dto/request/MenuRequestDto.java
Labels: fix

#140 feat: 필터수정
  src/main/java/com/example/springrider/config/filter/SessionLoginCheckFilter.java
Labels: feature

#141 Docs: README 작성
  README.md
Labels: docs

#142 docs: 프로젝트 소개 수정
  README.md
Labels: docs

#144 [#143] Feat/constant concept apply
  src/main/java/com/example/springrider/domain/cart/controller/CartController.java
  src/main/java/com/example/springrider/domain/cart/dto/request/UpdateCartItemRequestDto.java
  src/main/java/com/example/springrider/domain/cart/entity/CartItem.java
  src/main/java/com/example/springrider/domain/cart/enums/CartItemStatus.java
  src/main/java/com/example/springrider/domain/cart/service/CartService.java
  src/main/java/com/example/springrider/domain/order/enums/OrderCancelReason.java
  src/main/java/com/example/springrider/domain/order/enums/OrderStatus.java
  src/main/java/com/example/springrider/domain/order/service/OwnerOrderService.java
  src/main/java/com/example/springrider/domain/review/entity/Review.java
  src/main/java/com/example/springrider/domain/review/enums/Rating.java
  src/main/java/com/example/springrider/global/validation/EnumValidator.java
Labels: feature
